plugins {
    id 'java'
    id 'checkstyle'
    id 'io.spring.dependency-management' version "${gradleDependencyManagementVersion}" apply false
    id 'org.springframework.boot' version "${springBootVersion}" apply false
}

group = 'com.c4cometrue'

subprojects {
    apply plugin: 'java'
    apply plugin: 'checkstyle'
    apply plugin: 'io.spring.dependency-management'

    java {
        sourceCompatibility = JavaVersion.toVersion(javaVersion)
        targetCompatibility = JavaVersion.toVersion(javaVersion)
    }

    repositories {
        mavenCentral()
    }

    dependencyManagement {
        imports {
            mavenBom "org.springframework.boot:spring-boot-dependencies:${springBootVersion}"
        }
    }

    lombokDependencies(project)
    slf4jDependencies(project)

    // ✅ Checkstyle
    checkstyle {
        configFile = file("${rootDir}/naver-checkstyle.xml")
        configProperties = ["suppressionFile": "${rootDir}/naver-checkstyle-suppressions.xml"]
        toolVersion = checkstyleVersion
    }

    // ✅ JUnit 5 설정
    tasks.withType(Test).configureEach {
        useJUnitPlatform()
    }
}

def slf4jDependencies(Project project) {
    project.dependencies {
        implementation "org.slf4j:slf4j-api:${slf4jVersion}"
    }
}
def lombokDependencies(Project project) {
    project.dependencies {
        compileOnly "org.projectlombok:lombok:${lombokVersion}"
        annotationProcessor "org.projectlombok:lombok:${lombokVersion}"
    }
}


// 데이터베이스 의존성 추가
def databaseDependencies(Project project, String db = 'oracle') {
    project.dependencies {
        if (db == 'oracle') {
            runtimeOnly "com.oracle.database.jdbc:ojdbc8:${oracleVersion}"
        } else if (db == 'mysql') {
            runtimeOnly "mysql:mysql-connector-java:${mysqlVersion}"
        }
    }
}

// QueryDSL 설정을 위한 공통 함수
def configureQueryDsl(Project project) {
    def querydslDir = project.layout.buildDirectory.dir("generated/querydsl").get().asFile

    sourceSets {
        main {
            java {
                srcDir querydslDir
            }
        }
    }

    project.configurations {
        querydsl.extendsFrom compileClasspath
    }

    project.tasks.withType(JavaCompile).configureEach {
        options.compilerArgs += ["-parameters"]
        options.getGeneratedSourceOutputDirectory().set(querydslDir)
    }

    project.tasks.named("clean").configure {
        doFirst {
            delete querydslDir
        }
    }

    // QueryDSL 관련 태스크 의존성 명시적 설정
    project.tasks.matching { it.name == 'compileJava' }.configureEach {
        dependsOn project.tasks.matching { it.name.contains('querydsl') }
    }

    project.dependencies {
        implementation "com.querydsl:querydsl-jpa:${querydslVersion}:jakarta"
        annotationProcessor "com.querydsl:querydsl-apt:${querydslVersion}:jakarta"
        annotationProcessor "jakarta.annotation:jakarta.annotation-api:${jakartaAnnotationVersion}"
        annotationProcessor "jakarta.persistence:jakarta.persistence-api:${jakartaPersistenceVersion}"
    }
}

//---- 🏗️  Infra Layer ----
project(':member-infra') {
    configureQueryDsl(project)
    databaseDependencies(project)

    dependencies {
        implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

        implementation project(':common')
        implementation project(':member-domain')
    }
}

project(':main-account-infra') {
    configureQueryDsl(project)
    databaseDependencies(project)

    dependencies {
        implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
        implementation 'org.springframework.boot:spring-boot-starter-validation'

        implementation project(':common')
        implementation project(':main-account-domain')
        implementation project(':member-infra')
    }
}

project(':saving-account-infra') {
    configureQueryDsl(project)
    databaseDependencies(project)

    dependencies {
        implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
        implementation 'org.springframework.boot:spring-boot-starter-validation'

        implementation project(':common')
        implementation project(':saving-account-domain')
        implementation project(':main-account-infra')
        implementation project(':member-infra')
    }
}

project(':transfer-infra') {
    configureQueryDsl(project)
    databaseDependencies(project)

    dependencies {
        implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

        implementation project(':common')
        implementation project(':transfer-domain')
        implementation project(':member-domain')
        implementation project(':member-infra')
        implementation project(':main-account-infra')
        implementation project(':saving-account-infra')
    }
}

project(':transfer-log-infra') {
    configureQueryDsl(project)
    databaseDependencies(project)

    dependencies {
        implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

        implementation project(':common')
        implementation project(':transfer-log-domain')
    }
}

project(':dlq-infra') {
    configureQueryDsl(project)
    databaseDependencies(project)

    dependencies {
        implementation project(':common')
        implementation project(':transfer-log-domain')
        implementation project(':dlq-domain')

        implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    }
}

//---- 🌟 Domain Layer ----
project(':member-domain') {
    dependencies {
        implementation 'org.springframework:spring-context'

        implementation project(':common')
    }
}

project(':main-account-domain') {
    dependencies {
        implementation 'org.springframework:spring-context'

        implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
        implementation project(':member-domain')
        implementation project(':common')
    }
}

project(':saving-account-domain') {
    dependencies {
        implementation 'org.springframework:spring-context'

        implementation project(':main-account-domain')
        implementation project(':member-domain')
        implementation project(':common')
    }
}

project(':settlement-domain') {
    dependencies {
        implementation 'org.springframework:spring-context'
        implementation project(':common')
    }
}

project(':transfer-domain') {
    dependencies {
        implementation 'org.springframework:spring-context'
        implementation "org.springframework.boot:spring-boot-starter-data-jpa" // jakarta.persistenc 예외

        implementation project(':member-domain')
        implementation project(':main-account-domain')
        implementation project(':saving-account-domain')
        implementation project(':common')
    }
}

project(':transfer-log-domain') {
    dependencies {
        implementation 'org.springframework:spring-context'
        implementation "com.fasterxml.jackson.core:jackson-databind:${jacksonVersion}"

        implementation project(':common')
    }
}

project(':dlq-domain') {
    dependencies {
        implementation 'org.springframework:spring-context'

        implementation project(':common')
    }
}

project(':reminder') {
    dependencies {
        implementation 'org.springframework:spring-context'

        // slack
        implementation "com.slack.api:slack-api-client:${slackVersion}" // 슬랙 API 클라이언트

        implementation project(':member-domain')
        implementation project(':transfer-domain')
        implementation project(':common')
    }
}



//---- 🌐 Interface Layer ----
project(':interface') {
    dependencies {
        implementation "org.springframework.boot:spring-boot-starter-data-jpa"

        // swagger
        implementation "org.springdoc:springdoc-openapi-starter-webmvc-ui:${springdocVersion}"

        // Mapper
        implementation "org.mapstruct:mapstruct:${mapstructVersion}"
        annotationProcessor "org.mapstruct:mapstruct-processor:${mapstructVersion}"

        implementation project(':main-account-domain')
        implementation project(':member-domain')
        implementation project(':reminder')
        implementation project(':saving-account-domain')
        implementation project(':settlement-domain')
        implementation project(':transfer-domain')
        implementation project(':transfer-log-domain')
        implementation project(':dlq-domain')
        implementation project(':dlq-infra')  // 🔥 이 라인 추가
        implementation project(':common')
    }
}

project(':batch') {
    dependencies {
        implementation project(':interface')
        implementation project(':dlq-domain')
        implementation project(':transfer-log-domain')
        implementation project(':common')

        implementation "com.fasterxml.jackson.core:jackson-databind:${jacksonVersion}"
        implementation "org.springframework.boot:spring-boot-starter-batch"
    }
}

//---- 📚 Common Layer ----
project(':common') {
    dependencies {
        // Core Dependencies
        implementation 'org.springframework.boot:spring-boot-starter-web'
        implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
        implementation 'org.springframework.boot:spring-boot-starter-validation'
        implementation "com.fasterxml.jackson.core:jackson-annotations:${jacksonVersion}"

        implementation "com.querydsl:querydsl-jpa:${querydslVersion}:jakarta"
        annotationProcessor "com.querydsl:querydsl-apt:${querydslVersion}:jakarta"
        annotationProcessor "jakarta.annotation:jakarta.annotation-api:${jakartaAnnotationVersion}"
        annotationProcessor "jakarta.persistence:jakarta.persistence-api:${jakartaPersistenceVersion}"
    }
}

project(':app') {
    dependencies {
        // Spring Boot Actuator: 애플리케이션 모니터링 및 관리 엔드포인트 제공
        implementation 'org.springframework.boot:spring-boot-starter-actuator'

        // Micrometer Prometheus Registry: Actuator 메트릭을 Prometheus 형식으로 변환
        runtimeOnly 'io.micrometer:micrometer-registry-prometheus'

        // logstash
        implementation "net.logstash.logback:logstash-logback-encoder:${logstashVersion}"

        // swagger
        implementation "org.springdoc:springdoc-openapi-starter-webmvc-ui:${springdocVersion}"

        // Spring Data JPA
        implementation "org.springframework.boot:spring-boot-starter-data-jpa"

        // Test Dependencies
//        testImplementation platform("org.springframework.boot:spring-boot-dependencies")
//        testImplementation 'org.springframework.boot:spring-boot-starter-test'
//        testImplementation "org.junit.jupiter:junit-jupiter:${junitJupiterVersion}"
//        testImplementation "org.assertj:assertj-core:${assertjVersion}"
//
//        // Lombok for test
//        testCompileOnly "org.projectlombok:lombok:${lombokVersion}"
//        testAnnotationProcessor "org.projectlombok:lombok:${lombokVersion}"

        implementation project(':main-account-domain')
        implementation project(':main-account-infra')
        implementation project(':saving-account-domain')
        implementation project(':saving-account-infra')
        implementation project(':transfer-domain')
        implementation project(':transfer-infra')
        implementation project(':transfer-log-domain')
        implementation project(':transfer-log-infra')
        implementation project(':dlq-domain')
        implementation project(':dlq-infra')
        implementation project(':interface')
        implementation project(':common')
        implementation project(':batch')
    }
}
