//---- 🔌 플러그인 설정 ----
plugins {
    id 'java'
    id 'org.springframework.boot' version "${springBootVersion}"
    id 'io.spring.dependency-management' version "${gradleDependencyManagementVersion}"
    id 'checkstyle'
}

//---- 📦 모든 하위 프로젝트 공통 설정 ----
allprojects {
    apply plugin: 'java'
    apply plugin: 'checkstyle'
    apply plugin: 'io.spring.dependency-management'

    // 루트 프로젝트에서는 bootJar, bootRun 비활성화
    if (project == rootProject) {
        bootJar {
            enabled = false
        }
        bootRun {
            enabled = false
        }
    }

    java {
        sourceCompatibility = JavaVersion.valueOf("VERSION_${javaVersion}")
        targetCompatibility = JavaVersion.valueOf("VERSION_${javaVersion}")
    }

    group = 'com.c4cometrue'
    version = version

    repositories {
        mavenCentral()
    }

    // 📏 Checkstyle 설정
    checkstyle {
        configFile = file("${rootDir}/naver-checkstyle.xml")
        configProperties = ["suppressionFile": "${rootDir}/naver-checkstyle-suppressions.xml"]
        toolVersion = checkstyleVersion
    }

    // ✅ 테스트 설정
    tasks.withType(Test) {
        useJUnitPlatform()
    }
}

subprojects {
    DatabaseDependencies(project)

    dependencies {
        // Core Spring Boot Dependencies
        implementation "org.springframework.boot:spring-boot-starter:${springBootVersion}"
        implementation "org.springframework.boot:spring-boot-starter-aop:${springBootVersion}"
        implementation "org.springframework.boot:spring-boot-starter-web:${springBootVersion}"
        implementation "org.springframework.boot:spring-boot-starter-validation:${springBootVersion}"
        implementation "org.springframework.retry:spring-retry:${springRetryVersion}"

        // Lombok - 모든 모듈에서 사용
        compileOnly "org.projectlombok:lombok:${lombokVersion}"
        annotationProcessor "org.projectlombok:lombok:${lombokVersion}"

        // logstash
        implementation 'net.logstash.logback:logstash-logback-encoder:7.4'
    }
}

// JPA 및 데이터베이스 의존성 추가
def DatabaseDependencies(project) {
    project.dependencies {
//        runtimeOnly "mysql:mysql-connector-java:${mysqlVersion}"
        runtimeOnly "com.oracle.database.jdbc:ojdbc8:${oracleVersion}"
    }
}

// Infra 모듈 공통 설정
def configureInfraModule(project) {
    // JPA 및 데이터베이스 의존성 추가
    DatabaseDependencies(project)

    // QueryDSL 설정
    configureQueryDsl(project)

    project.dependencies {
        // Spring Data JPA
        implementation "org.springframework.boot:spring-boot-starter-data-jpa:${springBootVersion}"
    }
}

// QueryDSL 설정을 위한 공통 함수
def configureQueryDsl(project) {
//    def querydslDir = layout.buildDirectory.dir("generated/querydsl").get().asFile
    def querydslDir = new File(project.buildDir, "generated/querydsl") // 기존과 다르게 각 모듈의 buildDir 사용

    project.sourceSets {
        main.java.srcDirs += [querydslDir]
    }

    project.configurations {
        querydsl.extendsFrom compileClasspath
    }

    project.tasks.withType(JavaCompile) {
        options.compilerArgs += ["-parameters"]
        options.getGeneratedSourceOutputDirectory().set(querydslDir)
    }

    project.clean {
        delete querydslDir
    }

    // QueryDSL 관련 태스크 의존성 명시적 설정
    project.tasks.matching { it.name == 'compileJava' }.all {
        dependsOn project.tasks.matching { it.name.contains('querydsl') }
    }


    project.dependencies {
        implementation "com.querydsl:querydsl-jpa:${querydslVersion}:jakarta"
        annotationProcessor "com.querydsl:querydsl-apt:${querydslVersion}:jakarta"
        annotationProcessor "jakarta.annotation:jakarta.annotation-api:${jakartaAnnotationVersion}"
        annotationProcessor "jakarta.persistence:jakarta.persistence-api:${jakartaPersistenceVersion}"
    }
}

project(':app') {
    DatabaseDependencies(project)

    dependencies {
        // Spring Data JPA
        implementation "org.springframework.boot:spring-boot-starter-data-jpa:${springBootVersion}"

        // Test Dependencies
        testImplementation platform("org.springframework.boot:spring-boot-dependencies:${springBootVersion}")
        testImplementation 'org.springframework.boot:spring-boot-starter-test'
        testImplementation "org.junit.jupiter:junit-jupiter:${junitJupiterVersion}"
        testImplementation "org.assertj:assertj-core:${assertjVersion}"

        // Lombok for test
        testCompileOnly "org.projectlombok:lombok:${lombokVersion}"
        testAnnotationProcessor "org.projectlombok:lombok:${lombokVersion}"

        implementation project(':main-account-domain')
        implementation project(':saving-account-domain')
        implementation project(':transfer-domain')
        implementation project(':main-account-infra')
        implementation project(':saving-account-infra')
        implementation project(':transfer-infra')
    }
}

//---- 🏗️  Infra Layer ----
project(':member-infra') {
    configureInfraModule(project)

    dependencies {
        implementation project(':common')
        implementation project(':member-domain')
    }
}

project(':main-account-infra') {
    configureInfraModule(project)

    dependencies {
        implementation project(':common')
        implementation project(':main-account-domain')
        implementation project(':member-infra')
    }
}

project(':saving-account-infra') {
    configureInfraModule(project)

    dependencies {
        implementation project(':common')
        implementation project(':saving-account-domain')
        implementation project(':main-account-infra')
        implementation project(':member-infra')
    }
}

project(':transfer-infra') {
    configureInfraModule(project)

    dependencies {
        implementation project(':common')
        implementation project(':transfer-domain')
        implementation project(':member-domain')
        implementation project(':member-infra')
        implementation project(':main-account-infra')
        implementation project(':saving-account-infra')
    }
}

project(':transfer-log-infra') {
    configureInfraModule(project)

    dependencies {
        implementation project(':common')
        implementation project(':transfer-log-domain')
    }
}

//---- 🌟 Domain Layer ----
project(':member-domain') {
    dependencies {
        implementation project(':common')
    }
}

project(':main-account-domain') {
    dependencies {
        implementation project(':member-domain')
        implementation project(':common')
    }
}

project(':saving-account-domain') {
    dependencies {
        implementation project(':main-account-domain')
        implementation project(':member-domain')
        implementation project(':common')
    }
}

project(':settlement-domain') {
    dependencies {
        implementation project(':common')
    }
}

project(':transfer-domain') {
    dependencies {
        // jakarta.persistenc 예외
        implementation "org.springframework.boot:spring-boot-starter-data-jpa:${springBootVersion}"

        implementation project(':member-domain')
        implementation project(':main-account-domain')
        implementation project(':saving-account-domain')
        implementation project(':common')
    }
}

project(':transfer-log-domain') {
    dependencies {
        implementation project(':common')
    }
}

project(':reminder') {
    dependencies {
        implementation project(':member-domain')
        implementation project(':transfer-domain')
        implementation project(':common')
    }
}

//---- 🌐 Interface Layer ----
project(':interface') {
    dependencies {
        implementation "org.springframework:spring-tx:${springTxVersion}"

        // swagger
        implementation "org.springdoc:springdoc-openapi-starter-webmvc-ui:${springdocVersion}"

        // Mapper
        implementation "org.mapstruct:mapstruct:${mapstructVersion}"
        annotationProcessor "org.mapstruct:mapstruct-processor:${mapstructVersion}"

        implementation project(':main-account-domain')
        implementation project(':member-domain')
        implementation project(':reminder')
        implementation project(':saving-account-domain')
        implementation project(':settlement-domain')
        implementation project(':transfer-domain')
        implementation project(':transfer-log-domain')
        implementation project(':common')
    }
}

project(':batch') {
    dependencies {
        implementation project(':interface')
        implementation "org.springframework.boot:spring-boot-starter-batch:${springBootVersion}"
    }
}

//---- 📚 Common Layer ----
project(':common') {
    dependencies {
        configureInfraModule(project)

        // Core Dependencies
        implementation "org.springframework.boot:spring-boot-starter-aop:${springBootVersion}"
        implementation "com.fasterxml.jackson.core:jackson-annotations:${jacksonVersion}"
    }
}
