rootProject.name = 'assignment'

// Core Modules
include 'common'

// Infra Modules
include 'member-infra'
include 'main-account-infra'
include 'saving-account-infra'
include 'transfer-infra'
include 'transfer-log-infra'

// Domain Modules
include 'member-domain'
include 'main-account-domain'
include 'saving-account-domain'
include 'transfer-domain'
include 'transfer-log-domain'
include 'settlement-domain'

// Application Modules
include 'interface'
include 'batch'
include 'reminder'
