input {
    tcp {
        port => 5044
        codec => json
    }
}

output {
    elasticsearch {
      index => "application-logs-%{+YYYY.MM.dd}"
      hosts => "${ELASTIC_HOSTS}"
      user => "${ELASTIC_USER}"
      password => "${ELASTIC_PASSWORD}"
      ssl => true
      ssl_certificate_authorities => "certs/ca/ca.crt"
  }
}